services:
  backend:
    build: ./backend
    container_name: social_backend
    restart: always
    ports:
      - "${HTTP_PORT:-8000}:80"
      - "443:443"
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017

  reverb:
    build: ./backend
    container_name: social_reverb
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/var/www/html
    networks:
      - app_network
    depends_on:
      - mongodb
    command: php artisan reverb:start --host="0.0.0.0" --port="8080"

  frontend:
    build: ./frontend
    container_name: social_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app
      - /app/node_modules
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: social_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    profiles:
      - local

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: