# frontend/nginx.conf
server {
    listen 80;
    
    location / {
        # Carpeta donde Vite genera los archivos estáticos (dist)
        root /usr/share/nginx/html;
        index index.html;
        
        # Esta línea es VITAL: intenta cargar el archivo solicitado, 
        # si no existe, redirige a index.html para que React Router tome el control.
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para manejar errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}